### ISSUE TITLE
Invite screen displaying options no longer possible 

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#21] opened 2018-07-19 01:29 UTC
**Description**
After promoting another member of a shared list and demoting yourself, the buttons to promote yourself and demote the new owner are greyed out as expected, however re-opening the Invite screen will display those buttons as available even though clicking them does nothing. They are displaying the correct text but not the correct appearance.

**To Reproduce**
1. In a shared project that you own, promote another member then demote yourself
2. Observe the now greyed out buttons
3. Close Handball and re-open it and check the buttons on the Invite page
4. Open Handball on another machine and check the buttons on the Invite page

**Expected behavior**
Expected greyed out buttons to remain greyed out but instead they returned as though promotion/demotion never happened despite changing their text.

**Screenshots**
Example of buttons after promoting/demoting and then opening on a different machine.
![screen shot 2018-07-19 at 11 12 21 am](https://user-images.githubusercontent.com/41365436/42915968-1eed1438-8b46-11e8-8d1a-1bcb3dc1542c.png)

**Environment:**
 - MacBookAir5,1 
 - OS: macOS High Sierra 10.13.6
 - Handball Version: 2.0.0 RC

**Additional context**
Which brings me to my next point. I promoted you as owner of the Handball Thoughts project and then left it... A true Handball indeed! 👍

**Comment by Charlie9830** [comment] 2018-07-20 02:19
Couldn't reproduce the issue exactly, but did find and fix some dodgy button enable logic. Including the "Kick" button getting disabled twice, making it twice as dark as everything else.
These fixes should cover the original issue. Closing for now.

**Closed by Charlie9830** 2018-07-20 02:19 UTC
Labels: bug
