### ISSUE TITLE
Sharing Project causes all Tasks to disappear

### ISSUE THREAD

**Issue by RobH779** [Charlie9830/pounder#92] opened 2018-09-02 00:17 UTC
**Describe the bug**
After sharing a Project to 3rd member, all the Tasks inside the Project disappeared.

**What were you doing at the time?**
The project had 2 existing members and an assortment of tasks across 2 task lists. ALL of the tasks had been assigned to members. Added a new member (Princess LX) and then once I accepted the invitation all the tasks disappeared. Can't restore from backup as the most recent backup is over a week ago.

**Expected behavior**
Expected 3rd member to have access to all of our tasks.

**Screenshots**
Empty Task Lists just after accepting invite on Princess LX account.
![screen shot 2018-08-30 at 6 03 05 pm](https://user-images.githubusercontent.com/41365436/44950925-0ad8a680-ae99-11e8-8d30-63bd66767c4d.png)

**Version Information**
 - OS: macOS 10.13.6
 - Version 2.0.5

**Additional context**
Not sure if this is to do with all the Tasks having been assigned to other users when 3rd user joined or if it is just related to 3rd user issues (conflicts etc.) Or of course, none of the above.

**Comment by Charlie9830** [comment] 2018-09-02 01:16
Looks like something has gone wrong with the Security Rules that control access to different parts of the Database. Although the issue is fixed I am going to keep this open and add it to the list of things to look at in the next release.

**Comment by RobH779** [comment] 2018-09-02 02:35
It did happen again on a different project, but this time it just suddenly happened, not when I invited another member.

![screen shot 2018-09-02 at 12 26 21 pm](https://user-images.githubusercontent.com/41365436/44951626-2ef1b300-aeac-11e8-8581-f994e352a188.png)

Fixed it by adding a new task list.

**Comment by Charlie9830** [comment] 2018-10-31 09:53
I think I fixed this in 2.0.6 but forgot to close this issue. Closing it now.

**Closed by Charlie9830** 2018-10-31 09:53 UTC
Labels: bug
